// URL: www.freecontactform.com
// Version: Free RSVP Form V1
// Copyright (c) 2013 Stuart Cochrane
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
function $$(e){if(!has_id(e)&&!has_name(e)){alert("Field "+e+" does not exist!\n Form validation configuration error.");return false}if(has_id(e)){return document.getElementById(e).value}else{return}}function has_id(e){try{var t=document.getElementById(e).value}catch(n){return false}return true}function has_name(e){try{var t=cfrm.nm.type}catch(n){return false}return true}function $val(e){return document.getElementById(e)}function trim(e){$val(e).value=$val(e).value.replace(/^\s+/,"").replace(/\s+$/,"")}var required={field:[],add:function(e,t,n){this.field[this.field.length]=[e,t,n]},out:function(){return this.field},clear:function(){this.field=[]}};var validate={check:function(e){try{var t=document.getElementById("form_submit_button").value;document.getElementById("form_submit_button").value="Please Wait....."}catch(n){}var r="Please fix the following errors:\n\n";var i="";var s="";var o=true;for(var u=0;u<required.field.length;u++){if(this.checkit(required.field[u][0],required.field[u][1],e)){}else{if(required.field[u][1]=="RADIO_GROUP"||required.field[u][1]=="CHECKBOX_GROUP"||required.field[u][1]=="RADIO_SINGLE"||required.field[u][1]=="CHECKBOX_SINGLE"||required.field[u][1]=="SELECT_MULTIPLE"||required.field[u][1]=="SELECT"){i=" Nothing was selected"}else{i="Entered data is not valid"}r=r+required.field[u][2]+": "+i+"\n";if(has_id(required.field[u][0])&&s.length==0){s=required.field[u][0]}o=false}if(required.field[u][1]=="COMPARE"){try{var a=required.field[u][0].split(":");var f=$$(a[0]);var l=$$(a[1]);if(f==l){}else{i="Do not match";r=r+required.field[u][2]+": "+i+"\n";o=false}}catch(n){}}}if(!o){alert(r)}if(s.length>0){document.getElementById(s).focus()}if(o==false){try{document.getElementById("form_submit_button").value=t}catch(n){}}return o},checkit:function(e,t,n){"";false;if(t=="RADIO_GROUP"||t=="RADIO_SINGLE"||t=="CHECKBOX_GROUP"||t=="CHECKBOX_SINGLE"||t=="SELECT_MULTIPLE"||t=="SELECT"){}else{if(t=="COMPARE"){}else if(this.trim($$(e)).length<1){return false}}switch(t){case"RADIO_GROUP":case"CHECKBOX_GROUP":var r=n[e].length;ischecked=false;for(var i=0;i<r;i++){if(n[e][i].checked){ischecked=true}}return ischecked;break;case"COMPARE":return true;break;case"RADIO_SINGLE":case"CHECKBOX_SINGLE":if(n[e].checked==true){return true}else{return false}break;case"SELECT":case"SELECT_MULTIPLE":case"NOT_EMPTY":if(this.trim($$(e)).length<1){return false}else{return true}break;case"ALPHA":exp=/^[A-Za-z]+$/;if($$(e).match(exp)==null){return false}else{return true}break;case"ALPHASPACE":exp=/^[A-Za-z ]+$/;if($$(e).match(exp)==null){return false}else{return true}break;case"NUMERIC":exp=/^[0-9]+$/;if($$(e).match(exp)==null){return false}else{return true}break;case"NUMERICPLUS":exp=/^[0-9 +-.]+$/;if($$(e).match(exp)==null){return false}else{return true}break;case"ALPHANUM":exp=/^[a-zA-Z0-9]+$/;if($$(e).match(exp)==null){return false}else{return true}break;case"ALPHANUMSPAC
